Update to LSP4MP 0.13.3
redhat-developer/quarkus-ls pull request #1035
Opened 2024-12-04 18:15 UTC by rgrunber

- ProjectLabelTest should import all test projects initially (@BeforeClass) as now, load{Maven,Gradle}Project will clear any previously imported test projects
- RenardeJaxRSTest artifactID should match project folder, and the .project/.classpath files should not be present
- Fix testcases

2024-12-04 19:06 UTC, datho7561 commented
There's a test that failing consistently: `PropertiesManagerLocationTest.usingVertxTest`

2024-12-04 21:07 UTC, rgrunber commented
I think it's worth investigating

```
ConfigItemIntBoolDefaultValueTest.configItemIntBoolDefaultValueTest:42 expected:<276> but was:<273>
MicroProfileConfigPropertyTest.configQuickstartFromClasspath:37 expected:<276> but was:<273>
```

before merging. They only fail in the GHA job, and never locally so I suspect something about the GHA configuration.

2024-12-05 15:37 UTC, rgrunber commented
> ```
> ConfigItemIntBoolDefaultValueTest.configItemIntBoolDefaultValueTest:42 expected:<276> but was:<273>
> MicroProfileConfigPropertyTest.configQuickstartFromClasspath:37 expected:<276> but was:<273>
> ```

Thanks to @datho7561 for helping me narrow down the issue. Specifically,

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/452a5de1ca83d1641d9a537417c71a531c36f831/org.eclipse.jdt.core/model/org/eclipse/jdt/core/IJavaProject.java#L281-L295

https://github.com/eclipse/lsp4mp/blob/1ba1bcc32da25562b6ee7b42770d5c1539abf85a/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/JDTTypeUtils.java#L45-L51

A progress monitor needs to be passed in to correctly resolve secondary types.

2024-12-05 16:04 UTC, datho7561 requested changes

2024-12-05 16:04 UTC, datho7561 commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/PropertiesManagerLocationTest.java
> +	public static void setupTetststs() throws CoreException, Exception {
It might be a good idea to fix this name (this was my fault, sorry)

2024-12-05 16:20 UTC, datho7561 approved these changes
Looks good. Thanks, Roland!

2024-12-05 16:20 UTC, merged