Provide completion for cache name in configuration file
redhat-developer/quarkus-ls pull request #408
Opened 2021-08-02 14:48 UTC by angelozerr

Provide completion for cache name in configuration file

Fixes #404

Signed-off-by: azerr <azerr@redhat.com>

2021-08-02 15:18 UTC, angelozerr commented
It should starts working. You can play with https://github.com/quarkusio/quarkus-quickstarts/tree/main/cache-quickstart

I need to clean my code and write tests.

2021-08-03 14:56 UTC, angelozerr commented
This PR requires the LSP4MP PR https://github.com/eclipse/lsp4mp/pull/159 which fixes the bug of disapear of quarkus cache properties as soon as you update a Java file.

2021-08-04 16:30 UTC, angelozerr commented
Tests has been writen.

2021-08-04 21:03 UTC, datho7561 requested changes

2021-08-05 10:02 UTC, angelozerr commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/cache-quickstart/src/main/docker/Dockerfile.legacy-jar
> +####
fixed

2021-08-05 10:02 UTC, angelozerr commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/cache-quickstart/src/main/docker/Dockerfile.native
> +####
fixed

2021-08-05 10:02 UTC, angelozerr commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/cache-quickstart/src/main/resources/META-INF/resources/index.html
> +<!DOCTYPE html>
fixed

2021-08-05 10:02 UTC, angelozerr commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/cache/properties/QuarkusCacheResultProvider.java
> +/*******************************************************************************
fixed

2021-08-05 10:03 UTC, angelozerr commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusSearchContext.java
> +	 * Returns by default {*}.
Try to improve it, please tell me if it's enough.

2021-08-05 15:04 UTC, datho7561 commented on quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusSearchContext.java
> +	 * Returns by default {*}.
Yes, it look good now.

2021-08-05 15:50 UTC, datho7561 commented
Sometimes I run into a case where I set up an endpoint that caches a result and confirm the caching is working (i.e. there is no delay on the second request). However, I still don't get auto-completion for the cache properties with the cache name filled. When this is happening, sometimes it gives no cache related properties, and sometimes it gives the default `{*}` property. I'll try to come up with steps to reproduce this issue.

2021-08-05 15:59 UTC, angelozerr commented
Ate you using my patch https://github.com/eclipse/lsp4mp/pull/159 ?

2021-08-05 16:07 UTC, datho7561 commented
Yes, I double checked that I was using the latest lsp4mp, which has your changes in it.

2021-08-05 17:18 UTC, datho7561 commented
I can't reproduce it reliably, so I think its probably okay to ignore for now.

2021-08-05 17:18 UTC, datho7561 approved these changes

2021-08-05 17:23 UTC, merged

2021-08-05 17:28 UTC, angelozerr commented
> I can't reproduce it reliably, so I think its probably okay to ignore for now.

Thanks for the merge. It's annoying that you cannot reproduce the problem. I will try to play with the feature and try to reproduce the problem.