Added validation severity setting for Qute `UndefinedProperty`
redhat-developer/quarkus-ls pull request #539
Opened 2022-01-13 15:37 UTC by AlexXuChen

Added validation severity setting for `UndefinedProperty` Qute error code.

Part of #451

Signed-off-by: Alexander Chen <alchen@redhat.com>

2022-01-13 18:43 UTC, angelozerr requested changes

2022-01-13 18:43 UTC, angelozerr commented on qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/.classpath
> +<classpath>
Dont updta this file

2022-01-13 18:43 UTC, angelozerr commented on qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/ItemResource/items.qute.html
> +            {item or 'John'}
Dont update this file

2022-01-13 18:43 UTC, angelozerr commented on qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/ItemResource/items.qute.html
> +<title>Qute - Items</title>
Dont update this file

2022-01-13 18:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
> +	private void validateSyntaxProperty(QuteValidationSettings validationSettings) {
I suppose its just for testing severity?

2022-01-13 18:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
> +
Rename undefined to undefinedVariable

2022-01-13 23:09 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
> +	public List<String> getExcluded() {
remove

2022-01-13 23:09 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
> +	public void setExcluded(List<String> excluded) {
remove

2022-01-13 23:09 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
> +	public DiagnosticSeverity getDiagnosticSeverity(String propertyName) {
remove

2022-01-13 23:09 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
> +	private boolean isExcluded(String propertyName) {
remove

2022-01-13 23:14 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
> +	private QuteValidationTypeSettings undefinedVariable;
Replace equals and hashCode with:

	```
@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (enabled ? 1231 : 1237);
		result = prime * result + ((undefinedVariable == null) ? 0 : undefinedVariable.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QuteValidationSettings other = (QuteValidationSettings) obj;
		if (enabled != other.enabled)
			return false;
		if (undefinedVariable == null) {
			if (other.undefinedVariable != null)
				return false;
		} else if (!undefinedVariable.equals(other.undefinedVariable))
			return false;
		return true;
	}
```

Please note that this code has been generated by Eclipse IDE "Source / Generate hashCode() and equals()..."

2022-01-13 23:17 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
> +
Add

```java
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((severity == null) ? 0 : severity.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QuteValidationTypeSettings other = (QuteValidationTypeSettings) obj;
		if (severity == null) {
			if (other.severity != null)
				return false;
		} else if (!severity.equals(other.severity))
			return false;
		return true;
	}

```

2022-01-14 10:52 UTC, angelozerr commented
@AlexXuChen here a branch which shouldwork https://github.com/angelozerr/quarkus-ls/tree/539-fix

I suggest that you copy/paste in your PR the Java file from https://github.com/angelozerr/quarkus-ls/blob/539-fix/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java

And for me it's working, here a demo:

![SeverityDemo](https://user-images.githubusercontent.com/1932211/149503895-eabf048c-2cb6-4020-a5ed-c73c2f31c902.gif)

2022-02-03 12:45 UTC, angelozerr commented
@AlexXuChen could you please:

 * resolve conflicts
 * rename UndefinedVariable with UndefinedObject for error code and settings please and for the error message to (don't use variable but object)

2022-03-04 10:52 UTC, fbricon commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
> +		none, error, warning;
s/none/ignore

2022-03-04 15:48 UTC, closed without merging

2022-03-04 15:48 UTC, AlexXuChen commented
Will restart after https://github.com/redhat-developer/quarkus-ls/pull/578 is merged