When Template is constructor-injected, @Location is ignored
redhat-developer/quarkus-ls pull request #653
Opened 2022-06-07 09:28 UTC by angelozerr

When Template is constructor-injected, @Location is ignored

Fixes #637

Signed-off-by: azerr <azerr@redhat.com>

2022-07-05 17:10 UTC, angelozerr commented
The PR can be reviewed now. Here a demo:

![LocationInConstructorDemo](https://user-images.githubusercontent.com/1932211/177380769-282e38b5-48db-4801-82a5-dace2f3e0666.gif)

2022-07-05 20:22 UTC, datho7561 requested changes

2022-07-06 06:47 UTC, angelozerr commented on qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/AnnotationLocationSupport.java
> +* Copyright (c) 2021 Red Hat Inc. and others.
fixed

2022-07-06 13:16 UTC, datho7561 approved these changes

2022-07-06 13:21 UTC, merged