Completion should generate only start section when empty end section is found
redhat-developer/quarkus-ls pull request #807
Opened 2023-03-01 15:14 UTC by angelozerr

Generate only start section when empty end section is foundCompletion should generate only start section when empty end section is
found

Fixes #805

Signed-off-by: azerr <azerr@redhat.com>

2023-03-01 21:21 UTC, angelozerr commented
@JessicaJHee here a new PR which do the samething than PR https://github.com/redhat-developer/quarkus-ls/pull/806 but without updating end tag section (since `{/}` is a valid end section). Here a demo:

![SnippetCompletionOnStartTag](https://user-images.githubusercontent.com/1932211/222267629-7a692e0f-87eb-4914-a149-beded8fbfb72.gif)

2023-03-02 09:13 UTC, angelozerr commented
The code of this PT should be clean, you can review it.

2023-03-02 14:05 UTC, datho7561 commented
If you have an unnamed close tag right after what you're writing, then it will never generate a close tag for tag completion, even if there aren't enough unnamed close tags to match the content you are generating:

![DoesntGenerateCloseTag](https://user-images.githubusercontent.com/22376627/222450494-725ca4ab-318a-4864-a071-699a487e61d0.gif)

2023-03-02 19:38 UTC, angelozerr commented
> If you have an unnamed close tag right after what you're writing, then it will never generate a close tag for tag completion, even if there aren't enough unnamed close tags to match the content you are generating:

I have improved template parser to take care of this usecase. Please retry it.

2023-03-02 20:02 UTC, angelozerr commented
@JessicaJHee could you check if it is working with surround please.

2023-03-02 20:45 UTC, datho7561 commented
Given the following template:

```


|{#each items}

{#each items}
  {it.name}
{/each}

{#each items}

{#each items}
  {it.name}
{/each}



{/}|
```

If I select between the two `|`, then I get a lot of code action failure notifications

2023-03-02 21:12 UTC, JessicaJHee approved these changes
LGTM, works well with surround with command! Thank you for writing lots of tests :)

2023-03-03 12:38 UTC, angelozerr commented
According [this comment](https://github.com/redhat-developer/quarkus-ls/pull/807#issuecomment-1452519160) it is not a good idea to change the behavior of the parser.

I revert my change and to fix the original issue  

```html
{#each items}
	{#|}
{/}
```

which didn't generate the full content of the snippet (only the first part of the section), I check if parent section of {# is closed. In this case, #each is not closed because the `{/}` is linked to `{#`. As parent section of `{#` (which is the #each) is not closed, the full content of the snippet must be generated.

@datho7561 please retry it and I suggest that you get https://github.com/redhat-developer/vscode-quarkus/pull/585 to play with surround too.

2023-03-03 12:41 UTC, angelozerr commented
Here a demo:

![SurroundSection](https://user-images.githubusercontent.com/1932211/222722846-268462a8-6472-4872-846a-6712b7a6399a.gif)

2023-03-03 16:28 UTC, datho7561 commented
Seems pretty good so far, I'm going to try it out with https://github.com/redhat-developer/vscode-quarkus/pull/585 and see how that goes...

2023-03-03 17:32 UTC, datho7561 requested changes
This works very well. I found a few spots where the code could be cleaned up a bit, but nothing major. Feel free to merge after you've addressed the comments.

2023-03-03 17:42 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
> +	 * Returns true if the given section has an empty end section {/] and false
fixed

2023-03-03 17:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/tags/QuteSnippetContentProvider.java
> + * Snippet content provider customizer foe Qute sections used to generate..
I have updated Javadoc with a sample, hope you will understand more.

2023-03-03 17:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/tags/QuteSnippetContentProvider.java
> +		return null;
Indeed :) Good catch.

2023-03-03 17:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/tags/QuteSnippetContentProvider.java
> +				// Check if there is a parent section which is not cloded, in this case the {\}
fixed

2023-03-03 17:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/tags/QuteSnippetContentProvider.java
> +		// if (currentNode.isText()) {
fixed

2023-03-03 19:14 UTC, datho7561 approved these changes
Looks good. Thanks, Angelo!

2023-03-03 19:15 UTC, merged