Support for #include #insert
redhat-developer/quarkus-ls pull request #810
Opened 2023-03-08 10:57 UTC by angelozerr

Support for #include #insert

Fixes #438

2023-03-09 08:12 UTC, angelozerr commented
the 
![QuteValidationWithClosedTemplate](https://user-images.githubusercontent.com/1932211/223959997-e9cce96e-7ab1-42cd-b557-d490b0e5a167.gif)

If you open a Qute template (just to start the Qute LS) ,and you close it (or not), and you wait for several  seconds, you should see all Qute errors of the project in the PROBLEMS view: 

![image](https://user-images.githubusercontent.com/1932211/223960480-9f351ab4-988f-4f0b-bb77-e7a5014c964f.png)

2023-03-10 08:20 UTC, angelozerr commented
@mkouba @FroMage I'm supporting completion for template ids in #include. Here a screenshot with the https://github.com/FroMage/quarkus-renarde-todo/blob/7784cba6de7f31e937726eec6725df3c95eca1f6/src/main/resources/templates/Login/login.html#L1

![image](https://user-images.githubusercontent.com/1932211/224260692-78d9ec16-a848-4eb9-9aaf-851c90518289.png)

As you can see, the completion shows the `.html`, `.txt` extensions, but in doc https://quarkus.io/guides/qute-reference#include_helper sample doesn't use the `.html` file extension. So I assume that we can write:

`{#include base}` or `{#include base.html}`

My question is what is the prefered syntax (with or without html?) Completion should show:

 * 1) template id with file extension?
 * 2) template id without file extension?
 * 3) template id with and without file extension both?

Should we have a settings to decide if 1), 2), or 3) should be done?

2023-03-10 09:18 UTC, FroMage commented
Well, good question. I didn't know you could do `{#include base}` without extension. Does it find the correct extension in case of several alternatives?

- `{#include email}` in `Emails/hello.txt` will include `email.txt`
- `{#include email}` in `Emails/hello.html` will include `email.html`

I guess that's a question for @mkouba I never tried that. I should try it.

As for the completion, I'd start by suggesting that you put toplevel templates first, which will get you `main.html` (with or without extension, depending on the outcode of this discussion) first, because in my experience, includes are 100% always including base templates at the root, never anything else.

2023-03-10 09:29 UTC, mkouba commented
> Should we have a settings to decide if 1), 2), or 3) should be done?

That's a good question and I don't have a simple answer ;-).

> Well, good question. I didn't know you could do `{#include base}` without extension. Does it find the correct extension in case of several alternatives?
> 
>     * `{#include email}` in `Emails/hello.txt` will include `email.txt`
> 
>     * `{#include email}` in `Emails/hello.html` will include `email.html`
> 
> 
> I guess that's a question for @mkouba I never tried that. I should try it.

Currently, it does not reflect the selected variant/suffix of the including template but iterates over the suffixes defined in `quarkus.qute.suffixes`, i.e. the default value is `qute.html,qute.txt,html,txt` so the `{#include email}` will try `email`, `email.qute.html`, `email.qute.txt`, `email.html` and finally `email.txt`.

In theory, we could reflect this kind of information but if you think about it, when you're inside the `Emails/hello.html` then you know that you're going to include the `html` variant, right? That said, the variant without suffix is IMO easier to read. 

It might make sense to provide the file with suffix if multiple variants exists...

2023-03-13 08:57 UTC, angelozerr commented
> As for the completion, I'd start by suggesting that you put toplevel templates first,

Very good feedback! Done:

![image](https://user-images.githubusercontent.com/1932211/224653220-581bbfc1-9633-4a18-895d-c9de200a3d7b.png)

2023-03-13 09:00 UTC, angelozerr commented
Thanks @mkouba for your feedback.

If I understand your idea, completion should show template id without suffix, and for the case of conflicts like `email.txt`, `email.html`, completion should show file extension.

@FroMage do you like this idea?

2023-03-13 10:45 UTC, FroMage commented
That's a good idea, I think.

2023-03-14 09:07 UTC, angelozerr commented
> That's a good idea, I think.

Here the result:

![image](https://user-images.githubusercontent.com/1932211/224950831-916fef80-2662-481d-894d-0de6d04775e7.png)

2023-03-14 09:25 UTC, FroMage commented
Looks great!

2023-03-14 09:37 UTC, fbricon commented
looks like completion proposes the current template (Application/index), which sounds like a bad idea

2023-03-14 14:07 UTC, angelozerr commented
> Looks great!

Glad the feature please you.

>looks like completion proposes the current template (Application/index), which sounds like a bad idea

Good catch! Fixed:

![image](https://user-images.githubusercontent.com/1932211/225026858-5a6c2af3-cf36-496c-99b3-6996e4501662.png)

2023-03-14 14:10 UTC, datho7561 commented
The validation for unopened templates doesn't appear until you open the first Qute template. Is this intentional? I think it could be interesting to validate all the templates as soon as the language server is able to.

2023-03-14 16:23 UTC, JessicaJHee reviewed
I've played around with deleting and restoring the templates and validation is working as expected! I wonder if it's a good idea to show the elements we could insert in the completion first? (i.e., have `title` show up before the suggested sections)
![Screenshot from 2023-03-14 12-08-09](https://user-images.githubusercontent.com/73968480/225069262-d9df4f42-70af-498d-844a-20b2c319a3a0.png)

I also was wondering if we support the simple example in https://quarkus.io/guides/qute-reference#include_helper. I'm not quite sure how it works.

2023-03-14 17:28 UTC, datho7561 commented
> It should work, what is your problem?

Maybe this is a different issue, but what I'm seeing is if I have the template `"other-template.html"`:

```qute-html
<h3>{#insert myTitle}MY TITLE :D{/}</h3>

<p>
{#insert}
    this is the paragraph used in this template
{/insert}
</p>
```

Then that means I can pass in a `myTitle` when I `{#include}` the template that will replace the `"MY TITLE :D"` value:

```qute-html
{#include other-template.html myTitle="New Title"}
  Content
{/}
```

However, right now we don't have completion or validation for `myTitle` when we include `"other-template.html"`. Is this expected? If so, then I think it's a good idea to open issues for that.

2023-03-14 18:00 UTC, angelozerr commented
> However, right now we don't have completion or validation for myTitle when we include "other-template.html". Is this expected? If so, then I think it's a good idea to open issues for that.

Indeed parameter in include is not supported, please create a new issue for that.

2023-03-14 19:26 UTC, datho7561 requested changes

2023-03-14 19:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/WatchDir.java
> + * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
fixed

2023-03-14 19:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
> +		watchers.add(new FileSystemWatcher(Either.forLeft("**/*.json")));
fixed

2023-03-14 19:43 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteTextDocument.java
> +* Copyright (c) 2021 Red Hat Inc. and others.
fixed

2023-03-14 22:35 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectFilesWatcher.java
> +public class QuteProjectFilesWatcher extends WatchDir {
I must write a test with this support.

To test in vscode:

 * comment this line https://github.com/redhat-developer/quarkus-ls/pull/810/files#diff-854c916bc4ae147f987affa94adc4054d62afb789c45d2778a4d2b18164af4dfR134
 * comment this line https://github.com/redhat-developer/quarkus-ls/pull/810/files#diff-16409fc750922b54b0bd633df892f47718829028062ea36eb309e704b75b0ac2L131

2023-03-15 05:41 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
> +			if (fileEvent.getType() != FileChangeType.Changed) {
I did a new push and now FileEventType#Changed should work.

2023-03-15 05:41 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionForTemplateIds.java
> +			Map<String /* template if with short syntax (ex : base) */, List<QuteTextDocument> /*
fixed

2023-03-15 05:41 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
> +	private static String[] TEMPLATE_VARIANTS = { "", ".html", ".qute.html", ".json", ".qute.json", ".txt", ".qute.txt",
fixed

2023-03-15 08:47 UTC, FroMage commented
> Indeed parameter in include is not supported, please create a new issue for that.

That's now how we pass parameters to included files, though.

2023-03-15 12:40 UTC, datho7561 commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
> +			if (fileEvent.getType() != FileChangeType.Changed) {
If I fix an error in a file while using a different file, then the error marker goes away in the language client, but if I add an error to the file, then no errors are added to the file.

2023-03-16 02:37 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectFilesWatcher.java
> +public class QuteProjectFilesWatcher extends WatchDir {
@datho7561 I have written tests with / without  this LSP capability https://github.com/redhat-developer/quarkus-ls/pull/810/files#diff-45a8adb3bad6abdda88d002f45a2b22aa7574e9a08f4e10fc6fef91cfbecb95b (CI build is working).

I retried in vscode by updating this method https://github.com/redhat-developer/quarkus-ls/blob/c0fc3388a170e0f709df88a625ec85d3c89460cd/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ClientCapabilitiesWrapper.java#L93 (by forcing to return to false) and it works correctly.

Could you retry it please and if it doesn't work, could you give me your usecase. Thanks.

2023-03-16 02:39 UTC, angelozerr commented
> That's now how we pass parameters to included files, though.

Thanks for your feedback. We have created the issue for that https://github.com/redhat-developer/quarkus-ls/issues/815

2023-03-16 13:21 UTC, datho7561 commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectFilesWatcher.java
> +public class QuteProjectFilesWatcher extends WatchDir {
I don't seem to get any responses from the server (other than unmatched cancellation responses) when I force this method to return true.

2023-03-16 13:30 UTC, angelozerr commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectFilesWatcher.java
> +public class QuteProjectFilesWatcher extends WatchDir {
You need to force to **false**. vscode support it.

2023-03-16 14:19 UTC, datho7561 commented on qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectFilesWatcher.java
> +public class QuteProjectFilesWatcher extends WatchDir {
Does it work for you?

2023-03-16 15:05 UTC, datho7561 approved these changes
Looks good to me, and it's working well. Thanks, Angelo!

2023-03-16 15:06 UTC, merged